language: java
notifications:
  email: false
  slack:
    secure: te9ySngdiqOd5YPlXYfD4L5prtuHFaKxGxOWdp9jyLRvz4ekwNcuM5sIplytHQcUelUOC0ScJ3stL+8lp5oTe2sr/KBx5bbno92jRLJeuoKsKZMxI1YrBLZlUfVLufoASuxLzF8ktVFpqsH5TYkt4yiDoQK13eyaZQud8GdGJAxugrtLmaqnSZNWXvyIRPhEVb+Yancvy2LbItZSenVK7GoGtE7SHSVLKZ3jP701V1su4Fb6bTgAqNRtLtInwQKYGNIPpp0usrxDvY6JWqzEUU6p6NR1wxPS3p4Nnr/d4FmEYZSOn5f5kkuyRxGUzFRUGesrgVoqRQtmKdTve3FgM2GE8MwcfWaG+j5+mYCMockjHzzaNZpQnxCSLuLN8Ew/x/1DYTc8n2jGp38GGONzq9EZftdABGwa9r3WXvcd0LAbiwK74PaVkLg+QnI+K3vjSo5Ibl5HJ5XY9xD0Lv/9vaBQX/RH6qiL8aJLshF06LO+dEfBFEkxQdGZUk+FARA5kKvpZ5CX0GdU+KrDi7pCFS++Ls6SItD+8ZBRFldnJRXMtUEM0CKrE8O+ZNO/agnWNz1aYNq6k1CaLFkKR4yn4Hzsc1CCWRpqvYQ6nmaZb1hcE/+4bhb7ZMHQCK+Xp5gdm8QPX5KrI6jAeWKIVnGljTMe96I56OYVKn8wybJ0Of8=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true
  -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: HEt9ezJTskg8PGfhGgUhA67loe+hZdEqKydSFoj+p346wryEXJQQgWO+bxHv4s34DEyJWf7HNXQgv7rJpqjcRGh1Iew6dvMmAqJya61cuITGe7hlPLQcheD9/iF9zO9t2eJ1B6hKxT4znh6omU2g1c9wxXMdt97lYGA1cy1bmCUIP+DXnapMT9vAM5nkI5Ryft75QvE3SFM5H716/Cwr26NNmypQEqZaU9ydVtPAkxG4TUTYiY8r6C+O+B6zd9blWTBOArEUlbMREKKiWlcQScNhhwl4DFucSXqrQ//H0JN0oNiDmnn8tQsi8q9rkwiw/Q9Sc7JU89ufm6xZED3tDufsS/n2IjuPV1in8QG4BnbeDAKKYh/ssDra2clpGhjgkee86soz9Dn0ZuV3zPfuWEoEIFUcc9sY8TKunX/sU9s/1ODrgQz8sGmibhDMAJR24vJlHDQvfVj1UXivfKAHD0r8n7N1UBjVu1wRVU2hsM6FS618Es6+OS71SkwsXyJtME1CI369nKOBqM2JYFRSFJZzvDMZsJDQCi/Giki2FftZQDs0EQfV1oAmc7k55E9t522WrF787jcABVi2VZGaHnDdWDGEBtw7G3YA4TpHvkaHdl0JGMH1oAYcsXcDAuANHVLMFD118YatMsvY+uOTd8+O3VS0VNfpGBiljOcX6W8=
  - secure: bZeQFTgenk3FqY7p5FVYwxtjohC6maEIVvwLgqJD1A+zL23y0O5X9yt5saAHdEB8z0z002sAltyMmjB/A0eHHG3tPbjKm9XBYADNuGffygiSOn0lQEnj+aDyke+tQliSVF2xI2Q5E+5HQtCpahXlSmgnlvaA0HJDSppr8+xeefd35RHmG6+NBOxCQfzbHjef8G7V2xvUi0nFxWKj8of4RB3kE57OrcHx2LIi0zd23NQj9WqGaN06of+CYpwaMWbbheSgNgOAcEH5nZHssNPAER8Q98FwpHGOe7cWgxKBhl5xaUSa6dckl40fZgiI/wUfYijA5XuQ9fyXx6m4nM55CY7GvQux6rvy/PB/VjANa+KThDG1WW1HjX5FQZLua27LuczFcEP7kJPMmhmmsx1PJtphZ9o3tUYFbnRaNwXfFrWiQkOnq/ydjBEWnNGEsHaeRWHq+Yq4ZzAyWTjqDafZbhB2bxMgqv4Ljc8FB4e5c+ThLd3Ow7tK6VKJeTk6OaUXovxaM6pYNAeeeAGJi0zACTDE5Vr79zNysuKSjJNjwUPvnBXaWpg/h1blPl/pLN6odtmpnvNZ5EpDkDZ2Qf/fFOMX4Wal4F19ibldtl+yW+1WYTuuX5DtEc/nRyjs5pWA6e2dzSLTh/mYqYh6HkHOeg/D5uZUOh1A5uEF3NPMTlc=
