language: java
notifications:
  email: false
  slack:
    secure: Gef010A4dVIDFx739fns8oJJeCsHWtgcpVAMhy5AuGPoqw2PXA5/NKGaBHl8U9L4C4+dyMZL37rPdgP8P7aoez7nknr/+ZyGjFwYrVac8mr9LTml7gNc6ZdDaIE8WPLokrZ2SIFFTd/3syhHounOEeRA9WWBTMJUxlOscr5wAnKHC/Z+LpI0OENGOwSICcdLPbUVerF9Rf9UTvNNt5sXbTLYsxz+9pm5CNSrSQOxJAT7pJMypCuzLgDN+rUrd9C2y22tuvZPVGUkGkTcT2BYvgn3lG7Opar4RZi1PAzmcidUnpyw1z5zUZQSeewj5Vyo77K9a7BIkPt6i6L1QojUzAVHFLY8bEiQEXMy7fBPouavzw8r8wEyuofZm7k8LFNXjJuaB4V1M+ZDEhDWtZ4eVtQchotY4EFuLMwlfEwGVCffQ4p/AUb218VQ4bk6dQO/zs59ryfi/JsrQIa2+6YAkhpvwCJboLdMsGNZZg51W3t9OmNjc63rH2ChRH/m9pFTw+C7FDHB+Zf/sRLLBWhvwbGOPyTvz6tk7Inc0S9Qn/HGFJL7qSO9aMktXbUScKUDafBwbq9mkRltT/yCGgDR6n4AVTHZOUEjUTK8dcVhvuqpwsiAGgpF8YQl6xoC44LC0UGW4IyCdQnzmvRK/G3PdBgGpVFhrCJgwicSpiJELxI=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true
  -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: tRyigqvbvD3TLIkqgvKQCeupJGRs66QGaiKSBRNNj7xoCJsyROgfVGKN1lr6dagc8F2/U7q79ypTQwxVYPjmfw32W1zt5LFM+X0t/8bdKWTAs9Lsh/uXUfqX5T9UUfGDDgY4CMdFeN4ZIG0gBA3WK3Srm1UY1keJgeIO/lDt5sME9/fW0WamiaDdJriF5dyBKiAqPlF4bt8RhtmvHD87x+8Noxodadjcu7faN0ilwPBq03sVtsjeyZXANLiWccj+Z6D1TyWVRSPYT+hLOsLMSMoW5QV5AW6quaseb9SxAHHHMcroRpIx7zLKNokGh99zsbd0G9g1G/zw7427fjMnslVMS8vRjZlLVM+wTX8gKGwAsqkkCs95wCrMxCtY2pO10DgmagcAH0bXFfwRP+4Fm3Z/zXvrdWh7lJeXr5InRWT4xWQjHCd258K+o6CFe/vEtrcdKezbmNEhs9aulXb7r1AY8CyNO7jIjZlDHbsgLiBsuD2GYDipII7VfMD48Wlclxovd9N3tYZCuqAys4DhWr86G3CcAcANbijNwV/UXAxrGNBcQl9/VRUi4Ja0S/PWk/nrGV0u+mXT3KJvMI5QkX9vFokBdEuD7BY1hEq++nAlwwdEVd13j6FDgIFtd328gR3cljQG2B3nsm8q4SxWTkhswbPYCtoSXAeCHaBIZd4=
  - secure: yNOlRDxmaN0uHJX3XlnF+C2JnmTNBaoYvGOutJddsRL+AiWVwXm/3GRQSCdfg5qO9z/uQUYTLo4VuLUA8UMITevoNFVKb0qw2qaTevPPyku2gQpJ8+B/v0Udl90qSbbqqk1xEmi3ZLDqoeQSdwb9A5Y9y6404JmXzHh2pjpFPyY/YCol2KKFHgsWHPl1hmU1tEH34d/wEpyQ7vRdSmdJFwT+pEmDez/PMdneq5tlVB0z/HiCIQG96dhyyVKRKM77D93zraRLSrcb4iYCDi3vmlL02fC+cdzcg8I3Frfm6Mrj4wZdIvmbOfDujbLdgtYe4+YAVYZpyBTLMe5CzaDIQTbERv3JD301qjMibZZ0b9FN6uiZELbPgyT7yHY0fL5ynT03+bdmcHBC1/tSUVJQfCCyxrAWKDhWHEcF2OzrdyvAQfZDIIcSwLj2XIfMlUuvcULkuCZCqDSF7IZBhZyBwZ1txDnLFqWuxuRuwvGSpa+Ud/ihSuSEAkC9meiRGAQCFHJF8aG5kMbSjGSc9wgHLs1s88otK18vJ4a1AaSQd0xHdTZ6TkgHVC3AUv8ekrJkeo2NlqqebbBofceTRdHs0IsfAVCFViyyN1MDj5PITkhrtPJT1n7Zs7AR7a+xzvbVQAUf0ljxdXH9YFMOLFpOWWbHTm6ueOJJ/E99iZNZn00=
